#!/usr/bin/env python3
"""
თემატური ენციკლოპედიის სახელების გასწორება - ფაზა 2.
ფონეტიკური გარდაქმნები და გაფართოებული ლექსიკონი.
"""
import json
import os
import re

DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data")

# გაფართოებული ლექსიკონი — ყველა დარჩენილი პრობლემური სახელი
EXTENDED_DICT = {
    # ა-ს სახელები
    "abaddon": "აბადონი", "abagtha": "აბაგთა", "abana": "აბანა",
    "abba": "აბბა", "abda": "აბდა", "abdeel": "აბდეელი",
    "abdi": "აბდი", "abdiel": "აბდიელი", "abdon": "აბდონი",
    "abed-nego": "აბედ-ნეგო", "abel": "აბელი",
    "abel-beth-maachah": "აბელ-ბეთ-მააქა", "abel-meholah": "აბელ-მეჰოლა",
    "abel-mizraim": "აბელ-მიზრაიმი", "abez": "აბეზი",
    "abi": "აბი", "abi-albon": "აბი-ალბონი", "abia": "აბია",
    "abiah": "აბია", "abiasaph": "აბიასაფი", "abiathar": "აბიათარი",
    "abib": "აბიბი", "abida": "აბიდა", "abidah": "აბიდა",
    "abiel": "აბიელი", "abiezer": "აბიეზერი", "abigail": "აბიგაილი",
    "abihail": "აბიხაილი", "abihu": "აბიჰუ", "abihud": "აბიჰუდი",
    "abijah": "აბია", "abijam": "აბიჯამი", "abilene": "აბილენე",
    "abimael": "აბიმაელი", "abimelech": "აბიმელექი",
    "abinadab": "აბინადაბი", "abinoam": "აბინოამი",
    "abiram": "აბირამი", "abishag": "აბიშაგი", "abishai": "აბიშაი",
    "abishalom": "აბიშალომი", "abishua": "აბიშუა",
    "abishur": "აბიშური", "abital": "აბიტალი", "abitub": "აბიტუბი",
    "abiud": "აბიუდი", "abner": "აბნერი", "absalom": "აბსალომი",
    "accad": "აქადი", "accho": "აქო", "achaia": "აქაია",
    "achaicus": "აქაიკოსი", "achan": "აქანი", "achbor": "აქბორი",
    "achim": "აქიმი", "achish": "აქიში", "achmetha": "აქმეთა",
    "achor": "აქორი", "achsah": "აქსა", "achshaph": "აქშაფი",
    "achzib": "აქზიბი", "adadah": "ადადა", "adah": "ადა",
    "adaiah": "ადაია", "adalia": "ადალია", "adam": "ადამი",
    "adamah": "ადამა", "admah": "ადმა", "adnah": "ადნა",
    "adino": "ადინო", "adonijah": "ადონია", "adoniram": "ადონირამი",
    "adoni-zedek": "ადონი-ცედექი", "adrammelech": "ადრამმელექი",
    "adriel": "ადრიელი", "ahab": "ახაბი", "ahar": "ახარი",
    "aharah": "ახარა", "aharhel": "ახარჰელი", "ahasai": "ახასაი",
    "ahasbai": "ახასბაი", "ahasuerus": "ასუეროსი",
    "ahava": "ახავა", "ahaz": "ახაზი", "ahaziah": "ახაზია",
    "ahban": "ახბანი", "ahiah": "ახია", "ahiah-prophet": "ახია",
    "ahiam": "ახიამი", "ahian": "ახიანი", "ahiezer": "ახიეზერი",
    "ahi-hud": "ახიჰუდი", "ahihud": "ახიჰუდი",
    "ahikam": "ახიკამი", "ahilud": "ახილუდი", "ahimaaz": "ახიმააზი",
    "ahiman": "ახიმანი", "ahimelech": "ახიმელექი",
    "ahimoth": "ახიმოთი", "ahinadab": "ახინადაბი",
    "ahinoam": "ახინოამი", "ahio": "ახიო", "ahira": "ახირა",
    "ahiram": "ახირამი", "ahisamach": "ახისამახი",
    "ahishahar": "ახიშახარი", "ahithophel": "ახითოფელი",
    "ahi-tub": "ახიტუბი", "ahitub": "ახიტუბი",
    "ahlab": "ახლაბი", "ahlai": "ახლაი", "ahuzzath": "ახუზათი",
    "ai": "ღაი", "ajah": "აია", "akan": "აქანი",
    "akkub": "აქუბი", "allan": "ალანი", "allon": "ალონი",
    "allon-bachuth": "ალონ-ბახუთი", "almodad": "ალმოდადი",
    "almug": "ალმუგი", "alush": "ალუში", "amad": "ამადი",
    "amal": "ამალი", "amalek": "ამალეკი", "amam": "ამამი",
    "aman": "ამანი", "amariah": "ამარია", "amaiah": "ამაია",
    "amasa": "ამასა", "amashai": "ამაშაი", "amasa-son": "ამასა",
    "ami": "ამი", "amit": "ამიტი", "ammah": "ამა",
    "ammiel": "ამიელი", "amminadab": "ამინადაბი",
    "amminadib": "ამინადიბი", "ammon": "ამონი",
    "amnon": "ამნონი", "amok": "ამოქი", "amor": "ამორი",
    "amram": "ამრამი", "amraphel": "ამრაფელი",
    "anah": "ანა", "anaharath": "ანახარათი", "anak": "ანაკი",
    "anani": "ანანი", "ananiah": "ანანია", "anath": "ანათი",
    "anathoth": "ანათოთი", "anna": "ანა", "annas": "ანანია",
    "ano": "ანო", "another": "სხვა", "antioch": "ანტიოქია",
    "antipas": "ანტიპა", "antipatris": "ანტიპატრისი",
    "aphek": "აფექი", "apharsathchites": "აფარსათქები",
    "apharsites": "აფარსები", "aphik": "აფიქი",
    "apocalypse": "გამოცხადება", "apocrypha": "აპოკრიფი",
    "appaim": "აპაიმი", "appii": "აპიი", "appii-forum": "აპიის ფორუმი",
    "apple": "ვაშლი", "apples": "ვაშლები", "aram": "არამი",
    "aram-naharaim": "არამ-ნაჰარაიმი", "aram-maacah": "არამ-მააქა",
    "ararat": "არარატი", "arba": "არბა", "archelaus": "არქელაოსი",
    "archer": "მშვილდოსანი", "archi": "არქი", "ard": "არდი",
    "areli": "არელი", "areopagite": "არეოპაგელი", "areopagus": "არეოპაგი",
    "arimathea": "არიმათეა", "arioch": "არიოქი", "aristeus": "არისტეოსი",
    "ark": "კიდობანი", "ark-of-covenant": "აღთქმის კიდობანი",
    "armageddon": "არმაგედონი", "armoni": "არმონი",
    "arnan": "არნანი", "arnon": "არნონი", "arphaxad": "არფაქსადი",
    "artaxerxes": "არტაქსერქსე", "arvad": "არვადი",
    "asahel": "ასაელი", "asai": "ასაი", "asaph": "ასაფი",
    "asareel": "ასარეელი", "asarel": "ასარელი",
    "asbal": "ასბალი", "asena": "ასენა", "asenath": "ასენათი",
    "ashan": "აშანი", "ashbel": "აშბელი", "asher": "ასერი",
    "asherah": "აშერა", "ashima": "აშიმა", "ashkelon": "აშკელონი",
    "ashnah": "აშნა", "ashpenaz": "აშფენაზი", "ashtaroth": "აშთაროთი",
    "ashtoreth": "აშთორეთი", "ashur": "აშური", "asnah": "ასნა",
    "assos": "ასოსი", "assur": "ასური", "assyr": "ასური",
    "asyncritus": "ასინქრიტოსი", "atan": "ატანი",
    "athach": "ათახი", "athaliah": "ათალია", "athens": "ათენი",
    "atrip": "ატრიპი", "attalia": "ატალია", "augustus": "ავგუსტუსი",
    "author": "ავტორი", "avim": "ავიმი", "avnith": "ავნითი",
    "azaliah": "აზალია", "azaniah": "აზანია", "azarael": "აზარაელი",
    "azareel": "აზარეელი", "azariah": "აზარია",
    "azaz": "აზაზი", "azaziah": "აზაზია", "azer": "აზერი",
    "azgad": "აზგადი", "aziza": "აზიზა", "azmaveth": "აზმავეთი",
    "azmon": "აზმონი", "azor": "აზორი", "azotus": "აზოტოსი",
    "azriel": "აზრიელი", "azrikam": "აზრიკამი",
    # ბ
    "baal": "ბაალი", "baalah": "ბაალა", "baalath": "ბაალათი",
    "baalath-beer": "ბაალათ-ბეერი", "baal-berith": "ბაალ-ბერითი",
    "baal-gad": "ბაალ-გადი", "baal-hamon": "ბაალ-ჰამონი",
    "baal-hanan": "ბაალ-ჰანანი", "baal-hermon": "ბაალ-ჰერმონი",
    "baali": "ბაალი", "baalim": "ბაალიმი", "baal-peor": "ბაალ-ფეორი",
    "baal-perazim": "ბაალ-ფერაციმი", "baal-shalisha": "ბაალ-შალიშა",
    "baal-tamar": "ბაალ-თამარი", "baal-zebub": "ბაალ-ზებუბი",
    "baal-zebul": "ბაალ-ზებული", "baana": "ბაანა",
    "baanah": "ბაანა", "baara": "ბაარა", "baaseiah": "ბაასეია",
    "baasha": "ბააშა", "babe": "ჩვილი", "babel": "ბაბილონი",
    "baca": "ბაქა", "bahurim": "ბახურიმი", "bajith": "ბაიითი",
    "bakbakkar": "ბაქბაქარი", "bukki": "ბუქი", "bukkiah": "ბუქია",
    "balaam": "ბალაამი", "baladan": "ბალადანი", "balak": "ბალაქი",
    "bani": "ბანი", "barachel": "ბარაქელი", "barak": "ბარაქი",
    "barbarian": "ბარბაროსი", "bar-jesus": "ბარ-იესუ",
    "bar-jonah": "ბარ-იონა", "bar-joshua": "ბარ-იესო",
    "barnabas": "ბარნაბა", "barsabbas": "ბარსაბა",
    "bartimaeus": "ბართიმეოსი", "baruch": "ბარუქი",
    "barzillai": "ბარზილაი", "basha": "ბაშა", "bath": "ბათი",
    "bath-rabbim": "ბათ-რაბიმი", "bath-shua": "ბათ-შუა",
    "batter": "სატენი", "battering-ram": "სატენი",
    "bedad": "ბედადი", "bedeiah": "ბედეია", "bediah": "ბედია",
    "beelzebub": "ბეელზებული", "beeri": "ბეერი",
    "beeroth": "ბეეროთი", "beersheba": "ბეერ-შება",
    "beeri-hittite": "ბეერი", "beker": "ბექერი", "bekker": "ბექერი",
    "bel": "ბელი", "bela": "ბელა", "belah": "ბელა",
    "belial": "ბელიალი", "belshazzar": "ბელშაცარი",
    "ben": "ბენი", "ben-ammi": "ბენ-ამი", "ben-geber": "ბენ-გებერი",
    "ben-hadad": "ბენ-ჰადადი", "ben-hail": "ბენ-ხაილი",
    "ben-hanan": "ბენ-ჰანანი", "ben-heres": "ბენ-ჰერესი",
    "ben-hesed": "ბენ-ხესედი", "ben-hur": "ბენ-ხური",
    "benjamin": "ბენიამინი", "ben-deker": "ბენ-დექერი",
    "benaiah": "ბენაია", "benu": "ბენუ", "ben-zoheth": "ბენ-ზოხეთი",
    "beon": "ბეონი", "beor": "ბეორი", "bera": "ბერა",
    "bera": "ბერა", "beriah": "ბერია", "berodach-baladan": "ბეროდაქ-ბალადანი",
    "berothah": "ბეროთა", "berothite": "ბეროთელი",
    "beryl": "ბერილიონი", "besodeiah": "ბესოდეია",
    "besor": "ბესორი", "beta": "ბეთა", "beth": "ბეთი",
    "beth-anoth": "ბეთ-ანოთი", "beth-arabah": "ბეთ-არაბა",
    "beth-aven": "ბეთ-ავენი", "beth-azmaveth": "ბეთ-აზმავეთი",
    "beth-baal-meon": "ბეთ-ბაალ-მეონი", "beth-barah": "ბეთ-ბარა",
    "beth-birei": "ბეთ-ბირეი", "beth-car": "ბეთ-ქარი",
    "beth-dagon": "ბეთ-დაგონი", "beth-diblathaim": "ბეთ-დიბლათაიმი",
    "beth-eden": "ბეთ-ედენი", "beth-eked": "ბეთ-ექედი",
    "beth-el": "ბეთელი", "beth-ezel": "ბეთ-ეზელი",
    "beth-gader": "ბეთ-გადერი", "beth-gamul": "ბეთ-გამული",
    "beth-gilgal": "ბეთ-გილგალი", "beth-haccerem": "ბეთ-ჰაქერემი",
    "beth-haggan": "ბეთ-ჰაგანი", "beth-hajeshimoth": "ბეთ-ჰაიეშიმოთი",
    "beth-haran": "ბეთ-ჰარანი", "beth-hoglah": "ბეთ-ჰოგლა",
    "beth-horon": "ბეთ-ჰორონი", "beth-lebaoth": "ბეთ-ლებაოთი",
    "beth-leshem": "ბეთ-ლეშემი", "beth-maacah": "ბეთ-მააქა",
    "beth-marcaboth": "ბეთ-მარქაბოთი", "beth-meon": "ბეთ-მეონი",
    "beth-nimrah": "ბეთ-ნიმრა", "beth-palet": "ბეთ-ფალეთი",
    "beth-peor": "ბეთ-ფეორი", "beth-phage": "ბეთ-ფაგე",
    "beth-rapha": "ბეთ-რაფა", "beth-saida": "ბეთსაიდა",
    "beth-shan": "ბეთ-შაანი", "beth-shemesh": "ბეთ-შემეში",
    "beth-shean": "ბეთ-შეანი", "beth-tappuah": "ბეთ-თაფუა",
    "bethany": "ბეთანია", "bethel": "ბეთელი",
    "bether": "ბეთერი", "bethesda": "ბეთესდა",
    "bethlehem": "ბეთლემი", "bethlehem-judah": "ბეთლემ-იუდა",
    "bethsaida": "ბეთსაიდა", "bethuel": "ბეთუელი",
    "bethtappuah": "ბეთ-თაფუა", "betshean": "ბეთ-შეანი",
    "betrothal": "ნიშნობა", "betrothed": "დანიშნული",
    "buz": "ბუზი", "buzi": "ბუზი", "buzite": "ბუზელი",
    # გ-დ
    "gaal": "გაალი", "gaash": "გააში", "gaba": "გაბა",
    "gabriel": "გაბრიელი", "gad": "გადი", "gaddi": "გადი",
    "gaddiel": "გადიელი", "gahar": "გახარი", "gaius": "გაიოსი",
    "galal": "გალალი", "galilee": "გალილეა", "gallim": "გალიმი",
    "gammadim": "გამადიმი", "gamul": "გამული", "gaon": "გაონი",
    "gath": "გათი", "gath-hepher": "გათ-ხეფერი",
    "gath-rimmon": "გათ-რიმონი", "gaulon": "გაულონი",
    "gaza": "გაზა", "gazer": "გაზერი", "gazith": "გაზითი",
    "geba": "გება", "gebah": "გება", "gebal": "გებალი",
    "geber": "გებერი", "geburah": "გებურა", "gedaliah": "გედალია",
    "gederah": "გედერა", "gederathite": "გედერათელი",
    "gedor": "გედორი", "geharashim": "გეჰარაშიმი",
    "gehazi": "გეხაზი", "gemalli": "გემალი", "gemariah": "გემარია",
    "genealogy": "გენეალოგია", "genealogies": "გენეალოგიები",
    "genesar": "გენესარი", "genesareth": "გენესარეთი",
    "gennesaret": "გენესარეთი", "gentiles": "წარმართნი",
    "gera": "გერა", "gerah": "გერა", "gerar": "გერარი",
    "gergesene": "გერგესელი", "gergesenes": "გერგესელები",
    "gergesa": "გერგესა", "gershom": "გერშომი",
    "gershon": "გერშონი", "gershonite": "გერშონელი",
    "geshem": "გეშემი", "geshur": "გეშური", "geshurite": "გეშურელი",
    "gethsemane": "გეთსემანი", "geuel": "გეუელი",
    "gezer": "გეზერი", "gibbar": "გიბარი", "gibbethon": "გიბეთონი",
    "gibeah": "გიბეა", "gibcon": "გიბქონი", "gibea": "გიბეა",
    "gibeon": "გიბეონი", "gibeonite": "გიბეონელი",
    "giblites": "გიბლელები", "giddel": "გიდელი",
    "giddalti": "გიდალთი", "giddaltiel": "გიდალთიელი",
    "gijon": "გიხონი", "gilalai": "გილალაი", "gilboa": "გილბოა",
    "gilead": "გილყადი", "gileadite": "გილყადელი",
    "gilgal": "გილგალი", "gilonite": "გილონელი",
    "gimzo": "გიმზო", "ginath": "გინათი", "gittah-hepher": "გითა-ხეფერი",
    "gittaim": "გითაიმი", "gittite": "გითელი",
    "gizonite": "გიზონელი", "goad": "მათრახი",
    "goan": "გოანი", "gob": "გობი", "gog": "გოგი",
    "golan": "გოლანი", "gold": "ოქრო", "goliath": "გოლიათი",
    "gomorrah": "გომორა", "goshen": "გოშენი",
    "gospel": "სახარება", "gospels": "სახარებანი",
    "gospel-of-god": "ღმერთის სახარება", "gospel-of-christ": "ქრისტეს სახარება",
    "government": "მმართველობა", "governor": "მმართველი",
    "governors": "მმართველები",
    # ე-ზ
    "edom": "ედომი", "edomite": "ედომელი", "edomites": "ედომელები",
    "edom-king": "ედომის მეფე", "edrei": "ედრეი",
    "eg-laim": "ეგლაიმი", "eglaim": "ეგლაიმი",
    "eglath-shelishiyah": "ეგლათ-შელიშია",
    "eglon": "ეგლონი", "ekron": "ექრონი", "ekronite": "ექრონელი",
    "eldad": "ელდადი", "elder": "უხუცესი", "elders": "უხუცესნი",
    "el-elohe-israel": "ელ-ელოჰე-ისრაელი",
    "elah": "ელა", "elah-valley": "ელას ველი",
    "elam": "ელამი", "elamite": "ელამელი", "elamites": "ელამელები",
    "el-bethel": "ელ-ბეთელი", "eldaa": "ელდაა",
    "elder-of-reuel": "რაგუელის უხუცესი",
    "elealeh": "ელეალე", "eleasah": "ელეასა",
    "eleazar": "ელეაზარი", "eleazar-son": "ელეაზარი",
    "eleh": "ელე", "el-elohe": "ელ-ელოჰე",
    "elfered": "ელფერედი", "eli": "ელი",
    "eli-eho": "ელი-ეჰო", "eliah": "ელია",
    "eliahba": "ელიახბა", "eliah-son": "ელია",
    "eliakim": "ელიაკიმი", "elias": "ელია",
    "eliasaph": "ელიასაფი", "eliasheb": "ელიასიბი",
    "eliasaph-son": "ელიასაფი",
    "eliathah": "ელიათა", "elidad": "ელიდადი",
    "eliehoenai": "ელი-ჰო-ენაი", "eliehoeni": "ელი-ჰო-ენაი",
    "eliezer": "ელიეზერი", "eliel": "ელიელი",
    "eliel-son": "ელიელი", "elienai": "ელიენაი",
    "elijah": "ელია", "elijah-prophet": "ელია წინასწარმეტყველი",
    "elika": "ელიქა", "elim": "ელიმი",
    "elimelech": "ელიმელექი", "elioenai": "ელიოენაი",
    "eliphal": "ელიფალი", "eliphaz": "ელიფაზი",
    "elipheleh": "ელიფელე", "eliphelet": "ელიფელეთი",
    "elisabeth": "ელისაბედ", "elisaphan": "ელისაფანი",
    "elisha": "ელისე", "elishah": "ელისა",
    "elishama": "ელიშამა", "elishaphat": "ელიშაფატი",
    "elishua": "ელიშუა", "elisheba": "ელიშება",
    "elisheva": "ელიშება",
    "elkul": "ელქული", "ellem": "ელემი",
    "ellore": "ელორე", "elmodam": "ელმოდამი",
    "elnathan": "ელნათანი", "elnathan-son": "ელნათანი",
    "el-nathan": "ელნათანი",
    "elod": "ელოდი", "elo-i": "ელოი",
    "elohim": "ელოჰიმი", "el-eloah": "ელ-ელოა",
    "el-palet": "ელ-ფალეთი", "elpaale": "ელფაალე",
    "elpaale-son": "ელფაალე",
    "el-palet": "ელ-ფალეთი", "elpelet": "ელფელეთი",
    "eluzai": "ელუზაი", "elymas": "ელიმასი",
    "elyon": "ელიონი", "elzabad": "ელზაბადი",
    "emims": "ემიმები", "emmanuel": "ემანუელი",
    "emmaus": "ემაუსი", "emor": "ემორი",
    "endor": "ენ-დორი", "en-dor": "ენ-დორი",
    "en-eglaim": "ენ-ეგლაიმი", "en-gannim": "ენ-განიმი",
    "en-haddah": "ენ-ჰადა", "en-hakkore": "ენ-ჰაქორე",
    "en-hazor": "ენ-ხაცორი", "en-mishpat": "ენ-მიშფატი",
    "en-rogel": "ენ-როგელი", "en-shemesh": "ენ-შემეში",
    "en-tappuah": "ენ-თაფუა", "enaim": "ენაიმი",
    "epaenetus": "ეპაენეტოსი", "epaphras": "ეპაფრასი",
    "epaphroditus": "ეპაფროდიტე", "ephah": "ეფა",
    "epher": "ეფერი", "ephod": "ეფოდი", "ephraim": "ეფრემი",
    "ephraimite": "ეფრემელი", "ephratah": "ეფრათა",
    "ephrath": "ეფრათი", "ephrathite": "ეფრათელი",
    "ephron": "ეფრონი", "epicureans": "ეპიკურელები",
    "epiphanes": "ეპიფანე", "epoch": "ეპოქა",
    "er": "ერი", "era": "ერა", "eran": "ერანი",
    "erastus": "ერასტოსი", "er-i": "ერი",
    "eri": "ერი", "esau": "ესავი",
    "esdraelon": "ესდრაელონი", "esh-baal": "ეშ-ბაალი",
    "eshbaal": "ეშბაალი", "eshcol": "ეშქოლი",
    "eshcol-valley": "ეშქოლის ველი", "eshkalon": "აშკელონი",
    "eshtaol": "ეშთაოლი", "eshtemoa": "ეშთემოა",
    "eshtemoa-son": "ეშთემოა", "esli": "ესლი",
    "esrahiah": "ესრახია", "esrom": "ესრომი",
    "etam": "ეთამი", "etam-rock": "ეთამის კლდე",
    "ether": "ეთერი", "ethiopia": "ეთიოპია",
    "ethiopian": "ეთიოპელი", "ethiopians": "ეთიოპელები",
    "eth-kazin": "ეთ-ქაზინი", "ethnan": "ეთნანი",
    "eton": "ეტონი", "etna": "ეტნა",
    "eubulus": "ევბულოსი", "eunice": "ევნიკე",
    "eunuch": "საჭურისი", "eunuchs": "საჭურისები",
    "euphrates": "ევფრატი", "eurakylon": "ევრაკილონი",
    "eutychus": "ევტიქოსი", "evangelist": "მახარებელი",
    "evangelists": "მახარებლები", "eve": "ევა",
    "evil": "ბოროტება", "evil-merodach": "ევილ-მეროდაქი",
    "evil-spirit": "ბოროტი სული", "evil-spirits": "ბოროტი სულები",
    "exodus": "გამოსვლა", "exorcist": "ეგზორცისტი",
    "ezbon": "ეზბონი", "ezekiel": "ეზეკიელი",
    "ezer": "ეზერი", "ezra": "ეზრა",
    "ezrahite": "ეზრახელი", "ezri": "ეზრი",
    # ფონეტიკური გარდაქმნები დარჩენილი სახელებისთვის
    "hades": "ჯოჯოხეთი", "haggai": "ანგია", "hagi": "აგი",
    "hagi-tribe": "აგის ტომი", "hakkatan": "ჰაქათანი",
    "hakkoz": "ჰაქოზი", "hakupha": "ჰაქუფა",
    "halevi": "ჰალევი", "half-tribe": "ნახევარი ტომი",
    "hallal": "ჰალალი", "hallal-hallal": "ჰალალი",
    "ham": "ქამი", "haman": "ამანი",
    "hamath": "ხამათი", "hamathite": "ხამათელი",
    "hammedatha": "ჰამედათა", "hammoth-dor": "ჰამოთ-დორი",
    "hamonah": "ჰამონა", "hamon-gog": "ჰამონ-გოგი",
    "hamor": "ჰამორი", "hamuel": "ჰამუელი",
    "hamul": "ჰამული", "hamulite": "ჰამულელი",
    "hamutal": "ჰამუთალი", "hanan": "ჰანანი",
    "hananel": "ჰანანელი", "hanani": "ჰანანი",
    "hananiah": "ჰანანია", "hannah": "ანნა",
    "hanniel": "ჰანიელი", "hanon": "ჰანონი",
    "hanun": "ჰანუნი", "haphez": "ჰაფეზი",
    "happizzez": "ჰაპიზეზი", "hara": "ჰარა",
    "haradah": "ჰარადა", "haran": "ჰარანი",
    "harhas": "ჰარხასი", "harheres": "ჰარჰერესი",
    "harhur": "ჰარხური", "harim": "ჰარიმი",
    "harnepher": "ჰარნეფერი", "harod": "ჰაროდი",
    "harodite": "ჰაროდელი", "harosheth": "ჰაროშეთი",
    "harp": "ჩანგი", "harps": "ჩანგები",
    "haruphite": "ჰარუფელი", "haruz": "ჰარუზი",
    "hasadiah": "ჰასადია", "hasenuah": "ჰასენუა",
    "hashabiah": "ჰაშაბია", "hashabnah": "ჰაშაბნა",
    "hashabneiah": "ჰაშაბნეია", "hashem": "ჰაშემი",
    "hashmonah": "ჰაშმონა", "hashub": "ჰაშუბი",
    "hashubah": "ჰაშუბა", "hashum": "ჰაშუმი",
    "hashupha": "ჰაშუფა", "hasrah": "ჰასრა",
    "hatach": "ჰათაქი", "hatach-son": "ჰათაქი",
    "hauran": "ჰაურანი", "havilah": "ჰავილა",
    "havit": "ჰავითი", "hazor": "ჰაცორი",
    "hazor-hadattah": "ჰაცორ-ჰადათა",
    "head": "თავი", "healing": "განკურნება",
    "healing-gift": "განკურნების ნიჭი",
    "healing-miracle": "სასწაულებრივი განკურნება",
    "health": "ჯანმრთელობა", "hearing": "სმენა",
    "heart": "გული", "hearts": "გულები",
    "heathen": "წარმართნი", "heaven": "ზეცა",
    "heavens": "ზეცანი", "heavenly": "ზეციერი",
    "heber": "ჰებერი", "hebrew": "ებრაული",
    "hebrewess": "ებრელი ქალი", "hebrews": "ებრაელები",
    "hebrew-women": "ებრაელი ქალები",
    "hebron": "ხებრონი", "hebronite": "ხებრონელი",
    "hegai": "ჰეგაი", "heged": "ჰეგედი",
    "heifer": "მცირე ძროხა", "heifers": "მცირე ძროხები",
    "heir": "მემკვიდრე", "heirs": "მემკვიდრენი",
    "helam": "ჰელამი", "helbah": "ჰელბა",
    "helbon": "ჰელბონი", "heleb": "ჰელები",
    "heled": "ჰელედი", "helek": "ჰელექი",
    "helekite": "ჰელექელი", "helkai": "ჰელქაი",
    "helkath": "ჰელქათი", "helkath-hazzurim": "ჰელქათ-ჰაზურიმი",
    "hena": "ჰენა", "henadad": "ჰენადადი",
    "her": "მისი", "her-nazarite": "მისი ნაზირე",
    "herald": "მაუწყებელი", "herb": "მცენარე",
    "herbs": "მცენარეები", "herd": "ფარა",
    "herds": "ფარები", "herdsman": "მწყემსი",
    "herdsmen": "მწყემსები", "heresh": "ჰერეში",
    "heres": "ჰერესი", "hereth": "ჰერეთი",
    "hermon": "ჰერმონი", "hermonite": "ჰერმონელი",
    "herod": "ჰეროდე", "herodians": "ჰეროდიანელები",
    "herodion": "ჰეროდიონი", "herod-philip": "ჰეროდე ფილიპე",
    "herod-agrippa": "ჰეროდე აგრიპა", "herod-antipas": "ჰეროდე ანტიპა",
    "herodias": "ჰეროდიადა", "herodion": "ჰეროდიონი",
    "heron": "იალაღის ყანწა", "herons": "იალაღის ყანწები",
    "heshbon": "ხეშბონი", "heshmon": "ხეშმონი",
    "hesro": "ხესრო", "heth": "ხეთი",
    "hethite": "ხეთელი", "hethites": "ხეთელები",
    "hezekiah": "ეზეკია", "hezir": "ხეზირი",
    "hezrai": "ხეზრაი", "hezro": "ხეზრო",
    "hezekiah-king": "ეზეკია მეფე",
    "hiddai": "ჰიდაი", "hiddaikel": "ჰიდაიქელი",
    "hierapolis": "იერაპოლისი", "hieroglyphic": "იეროგლიფური",
    "high-priest": "მღვდელმთავარი", "high-priests": "მღვდელმთავრები",
    "hilal": "ჰილალი", "hilkiah": "ხილკია",
    "hill": "ბორცვი", "hills": "ბორცვები",
    "hill-country": "მთიანი მხარე", "hinnom": "ჰინომი",
    "hittites": "ხეთელები", "hivite": "ჰეველი",
    "hivites": "ჰეველები", "hobab": "ხობაბი",
    "hodesh": "ჰოდეში", "hodijah": "ჰოდია",
    "hodaviah": "ჰოდავია", "hoes": "სათხრელები",
    "hoglah": "ხოგლა", "hoglah-daughter": "ხოგლა",
    "hoham": "ჰოხამი", "holiness": "სიწმიდე",
    "holy": "წმიდა", "holy-one": "წმიდანი",
    "holy-ones": "წმიდანი", "holy-place": "წმიდა ადგილი",
    "holy-places": "წმიდა ადგილები", "holy-spirit": "სულიწმიდა",
    "holy-trinity": "წმიდა სამება",
    "homam": "ჰომამი", "homan": "ჰომანი",
    "hommam": "ჰომამი", "honesty": "პატიოსნება",
    "honey": "თაფლი", "honour": "პატივი",
    "hoof": "ჩლიქი", "hoofs": "ჩლიქები",
    "hook": "კავი", "hooks": "კავები",
    "hope": "იმედი", "hope-of": "იმედი",
    "hor": "ჰორი", "hor-hagidgad": "ჰორ-ჰაგიდგადი",
    "horam": "ჰორამი", "horeb": "ხორები",
    "horem": "ჰორემი", "hori": "ჰორი",
    "horite": "ჰორიელი", "horites": "ჰორიელები",
    "horn": "რქა", "horns": "რქები",
    "hornet": "ბზიზღალა", "horses": "ცხენები",
    "horon": "ჰორონი", "horonaim": "ჰორონაიმი",
    "horonite": "ჰორონელი", "hosea": "ოსია",
    "hoshaiah": "ჰოშაია", "hoshama": "ჰოშამა",
    "hoshea": "ოშეა", "host": "ლაშქარი",
    "host-of-heaven": "ზეციერი ლაშქარი",
    "hosts": "ლაშქრები", "house": "სახლი",
    "houses": "სახლები", "household": "სახლეული",
    "households": "სახლეულები", "house-of-god": "ღმერთის სახლი",
    "hovah": "ჰოვა", "hovah-son": "ჰოვა",
    "hovah-valley": "ჰოვას ველი", "hovi": "ჰოვი",
    "hukkok": "ჰუქოქი", "hul": "ჰული",
    "hulda": "ჰულდა", "huldah": "ჰულდა",
    "hulda-prophetess": "ჰულდა წინასწარმეტყველი",
    "humility": "მორჩილება", "humtah": "ჰუმთა",
    "hun": "ჰუნი", "hunting": "ნადირობა",
    "hur": "ხური", "hurai": "ხურაი",
    "huram": "ხურამი", "huri": "ხური",
    "hur-tabor": "ხურ-თაბორი", "hushah": "ხუშა",
    "hushai": "ხუშაი", "hushathite": "ხუშათელი",
    "hushim": "ხუშიმი", "husband": "ქმარი",
    "husbands": "ქმრები", "hymn": "გალობა",
    "hymns": "გალობები", "hypocrisy": "პირობითობა",
    "hypocrite": "პირობითი", "hypocrites": "პირობითნი",
    # ი
    "iam": "იამი", "ial": "იალი", "ib-har": "იბ-ხარი",
    "ibhar": "იბხარი", "ibez": "იბეზი",
    "ibl-eam": "იბლეამი", "ibleam": "იბლეამი",
    "ibn": "იბნი", "ibne": "იბნე",
    "ibni": "იბნი", "ibn-ja": "იბნია",
    "ibsan": "იბცანი", "ibzan": "იბცანი",
    "iccir": "იცირი", "iconium": "იკონიუმი",
    "iddo": "იდო", "iddo-prophet": "იდო წინასწარმეტყველი",
    "idbash": "იდბაში", "iddo-son": "იდო",
    "idol": "კერპი", "idols": "კერპები",
    "idolatry": "კერპთაყვანისმცემლობა",
    "idol-shepherd": "კერპი მწყემსი",
    "idumaea": "იდუმეა", "idumeans": "იდუმელები",
    "igal": "იგალი", "igeal": "იგეალი",
    "igil": "იგილი", "igjal": "იგჯალი",
    "ig-ja": "იგჯა", "iim": "იიმი",
    "ijim": "იიმი", "ijon": "იონი",
    "ikesh": "იქეში", "ikkesh": "იქეში",
    "ilai": "ილაი", "ilgah": "ილგა",
    "ill": "ავადმყოფი", "ills": "სენი",
    "im": "იმი", "image": "ხატი",
    "images": "ხატები", "image-of": "ხატი",
    "imam": "იმამი", "imana": "იმანა",
    "imlah": "იმლა", "imla-son": "იმლა",
    "immanuel": "ემანუელი", "imna": "იმნა",
    "imnah": "იმნა", "imnah-son": "იმნა",
    "imri": "იმრი", "imriel": "იმრიელი",
    "increase": "გაზრდა", "incense": "საკმელი",
    "incense-altar": "საკმლის სამსხვერპლო",
    "india": "ინდოეთი", "iniquity": "უსჯულოება",
    "iniquities": "უსჯულოებანი", "inheritance": "მემკვიდრეობა",
    "injury": "ზიანი", "ink": "მელანი",
    "in-laws": "მამდარნი", "inner": "შინაგანი",
    "inn": "სასტუმრო", "innkeeper": "სასტუმროს მეპატრონე",
    "inscriptions": "წარწერები", "inspired": "შთაგონებული",
    "instructor": "მასწავლებელი", "insults": "შეურაცხყოფა",
    "intreaty": "ვედრება", "inventions": "გამოგონებანი",
    "investigation": "გამოძიება", "iron": "რკინა",
    "iron-quarries": "რკინის სამტახროელი", "ironsmith": "რკინის მჭედელი",
    "iron-smith": "რკინის მჭედელი", "iron-workers": "რკინის მუშანი",
    "ir-nahash": "ირ-ნახაში", "irpeel": "ირფეელი",
    "ir-shemesh": "ირ-შემეში", "isaac": "ისააკი",
    "isaiah": "ესაია", "isaiah-prophet": "ესაია წინასწარმეტყველი",
    "iscah": "ისქა", "iscariot": "ისკარიოტელი",
    "ish": "იში", "ish-bosheth": "იშბოშეთი",
    "ish-hod": "იშ-ხოდი", "ish-i": "იში",
    "ish-maa": "იშმაა", "ishma": "იშმა",
    "ishmaiah": "იშმაია", "ishmael": "ისმაელი",
    "ishmaelite": "ისმაელელი", "ishmaelites": "ისმაელელები",
    "ish-maiah": "იშმაია", "ishod": "იშოდი",
    "ish-paphon": "იშ-ფაფონი", "ishpan": "იშფანი",
    "ish-tob": "იშ-ტობი", "ishtob": "იშ-ტობი",
    "ishuah": "იშუა", "ishui": "იშუი",
    "ishvah": "იშვა", "ishvi": "იშვი",
    "island": "კუნძული", "islands": "კუნძულები",
    "isle": "კუნძული", "isles": "კუნძულები",
    "israel": "ისრაელი", "israelite": "ისრაელელი",
    "israelites": "ისრაელელები", "issachar": "ისაქარი",
    "issachar-tribe": "ისაქარის ტომი", "issacharite": "ისაქარელი",
    "italian": "იტალიური", "italy": "იტალია",
    "ithai": "ითაი", "ithamar": "ითამარი",
    "ithlah": "ითლა", "ithnan": "ითნანი",
    "ithra": "ითრა", "ithran": "ითრანი",
    "ithre": "ითრე", "ithrite": "ითრელი",
    "itnah": "ითნა", "itnam": "ითნამი",
    "it-qa": "ითქა", "itta": "იტა",
    "ittai": "ითაი", "itter": "იტერი",
    "itte-ite": "იტე-იტე", "ittij": "ითიჯი",
    "iyyim": "იიმი", "iyye-abarim": "იიე-აბარიმი",
    "i-zehab": "ი-ზეჰაბი", "iz-har": "იზჰარი",
    "izhar": "იცჰარი", "izhar-son": "იცჰარი",
    "izrahiah": "იზრახია", "izrahite": "იზრახელი",
    "izri": "იზრი",
    # ინგლისური სიტყვები რომლებიც გაუტრანსლიტერებელია
    "happiness": "სიხარული", "hand": "ხელი",
    "hands": "ხელები", "hand-of-god": "ღმერთის ხელი",
    "harvest": "მკა", "harvests": "მკები",
    "harvest-feast": "მკის დღესასწაული",
    "harvest-time": "მკის დრო",
    "head-dress": "თავსაბურავი", "head-long": "თავდაყირა",
    "head-stone": "თავის ქადა", "heady": "თავხედი",
    "hearth": "ღუმელი", "hearth-god": "ღუმელის ღმერთი",
    "heathen": "წარმართნი", "heathenish": "წარმართული",
    "heaven": "ზეცა", "heavens": "ზეცანი",
    "heavenly": "ზეციერი", "heavenly-host": "ზეციერი ლაშქარი",
    "heavenly-kingdom": "ზეციერი სამეფო",
    "heavenly-places": "ზეციერი ადგილები",
    "hebrew": "ებრაული", "hebrewess": "ებრაელი ქალი",
    "hebrews": "ებრაელები",
    "hed": "ჰედი", "hedge": "ღობე",
    "hedges": "ღობეები", "hedged-in": "ღობით შემორაგული",
    "heel": "ქუსლი", "heels": "ქუსლები",
    "he-goat": "თხა", "he-goats": "თხები",
    "height": "სიმაღლე", "heights": "სიმაღლეები",
    "heir": "მემკვიდრე", "heirs": "მემკვიდრენი",
    "heirship": "მემკვიდრეობა",
    "helmet": "ჩაჩა", "helmets": "ჩაჩები",
    "help": "დახმარება", "helper": "დამხმარე",
    "helpers": "დამხმარენი", "helps": "დახმარებანი",
    "hem": "კალთა", "hems": "კალთები",
    "hen": "ქათამი", "henna": "ხენა",
    "her": "მისი", "herbs": "მცენარეები",
    "herd": "ფარა", "herds": "ფარები",
    "herdsman": "მწყემსი", "herdsmen": "მწყემსები",
    "heredity": "მემკვიდრეობა",
    "heresy": "მწვალებლობა", "heresies": "მწვალებლობანი",
    "heretic": "მწვალებელი", "heretics": "მწვალებლები",
    "hermon": "ჰერმონი",
    "herodias": "ჰეროდიადა", "herodians": "ჰეროდიანელები",
    "heron": "იალაღის ყანწა", "herons": "იალაღის ყანწები",
    "hew": "თლა", "hewn": "გამოთლილი",
    "hewn-stone": "გამოთლილი ქვა",
    "hexagon": "ექვსკუთხედი", "hey": "ჰეი",
    "hezekiah": "ეზეკია", "hezro": "ხეზრო",
    "hiding": "დამალვა", "hiding-place": "თავშესაფარი",
    "high": "მაღალი", "high-day": "დღესასწაული",
    "high-god": "მაღალი ღმერთი", "high-hand": "აღმაპყრობილი ხელი",
    "high-mountain": "მაღალი მთა",
    "high-officer": "მაღალი მოხელე",
    "high-priest": "მღვდელმთავარი", "high-priests": "მღვდელმთავრები",
    "high-sea": "ღრმა ზღვა", "high-way": "გზა",
    "highways": "გზები",
    "hilkiah": "ხილკია", "hill": "ბორცვი",
    "hills": "ბორცვები", "hill-country": "მთიანი მხარე",
    "hinnom": "ჰინომი", "hired": "დაქირავებული",
    "hireling": "მოსამსახურე", "hirelings": "მოსამსახურენი",
    "hissing": "სტვენა", "hittites": "ხეთელები",
    "hivites": "ჰეველები", "hoar": "ჭარბი",
    "hoary-head": "ჭარბთმიანი", "hobab": "ხობაბი",
    "hodesh": "ჰოდეში", "hodijah": "ჰოდია",
    "hoglah": "ხოგლა", "hoist": "აღმართვა",
    "hold": "სიმტკიცე", "holding": "ჭერა",
    "hole": "ხვრელი", "holes": "ხვრელები",
    "hollow": "ფუღურო", "holiness": "სიწმიდე",
    "holy": "წმიდა", "holy-one": "წმიდანი",
    "holy-ones": "წმიდანი", "holy-place": "წმიდა ადგილი",
    "holy-spirit": "სულიწმიდა", "holy-trinity": "წმიდა სამება",
    "home": "სახლი", "homeward": "სახლისკენ",
    "honest": "პატიოსანი", "honesty": "პატიოსნება",
    "honey": "თაფლი", "honeycomb": "ფიჭა",
    "honour": "პატივი", "honoured": "პატივცემული",
    "hood": "ქუდა", "hoof": "ჩლიქი",
    "hook": "კავი", "hooks": "კავები",
    "hope": "იმედი", "hopes": "იმედები",
    "hor-hagidgad": "ჰორ-ჰაგიდგადი", "horam": "ჰორამი",
    "horeb": "ხორები", "hori": "ჰორი",
    "horite": "ჰორიელი", "horites": "ჰორიელები",
    "horn": "რქა", "horns": "რქები",
    "hornet": "ბზიზღალა", "horror": "საშინელება",
    "horse": "ცხენი", "horses": "ცხენები",
    "horseback": "ცხენზე", "horseman": "მხედარი",
    "horsemen": "მხედრები", "horse-leech": "მარწუველა",
    "hosanna": "ოსანა", "hosea": "ოსია",
    "hoshama": "ჰოშამა", "hoshea": "ოშეა",
    "hospitable": "სტუმართმოყვარე", "hospitality": "სტუმართმოყვარეობა",
    "host": "ლაშქარი", "host-of-heaven": "ზეციერი ლაშქარი",
    "hosts": "ლაშქრები", "hostage": "მძევალი",
    "hostages": "მძევლები", "house": "სახლი",
    "houses": "სახლები", "household": "სახლეული",
    "households": "სახლეულები", "house-of-god": "ღმერთის სახლი",
    "house-of-judgment": "სამსჯავროს სახლი",
    "house-of-the-father": "მამის სახლი",
    "hovah": "ჰოვა", "hovi": "ჰოვი",
    "hukkok": "ჰუქოქი", "hul": "ჰული",
    "huldah": "ჰულდა", "human": "ადამიანური",
    "humanity": "კაცობრიობა", "humbling": "დამდაბლება",
    "humility": "მორჩილება", "hunger": "შიმშილი",
    "hungry": "მშიერი", "hunting": "ნადირობა",
    "hur": "ხური", "hurai": "ხურაი",
    "huram": "ხურამი", "huri": "ხური",
    "hushah": "ხუშა", "hushai": "ხუშაი",
    "hushathite": "ხუშათელი", "hushim": "ხუშიმი",
    "husband": "ქმარი", "husbands": "ქმრები",
    "husbandman": "მიწათმოქმედი", "husbandmen": "მიწათმოქმედნი",
    "hymn": "გალობა", "hymns": "გალობები",
    "hypocrisy": "პირობითობა", "hypocrite": "პირობითი",
    "hypocrites": "პირობითნი",
}


def main():
    print("=== თემატური ენციკლოპედიის სახელების გასწორება - ფაზა 2 ===\n")

    with open(os.path.join(DATA_DIR, "topic_names_ka.json"), "r", encoding="utf-8") as f:
        topics = json.load(f)

    fixed = 0
    not_found = 0

    for slug, current_name in topics.items():
        if slug in EXTENDED_DICT:
            new_name = EXTENDED_DICT[slug]
            if new_name != current_name:
                topics[slug] = new_name
                fixed += 1

    # დარჩენილი პრობლემური — ფონეტიკური გარდაქმნა
    phonetic_fixed = 0
    for slug, val in topics.items():
        if val.startswith("I ") or val.startswith("II ") or val.startswith("III ") or val.startswith("IV "):
            continue
        # მხოლოდ სახელები (არა კონცეფტები)
        is_name = slug[0].islower() and "-" not in slug and len(val) > 3
        if not is_name:
            continue
        # გადავამოწმოთ პრობლემურია თუ არა
        has_problem = "ჰ" in val or "ჩ" in val
        if not has_problem:
            continue
        # ფონეტიკური გარდაქმნა
        new_val = val
        # 1. ბოლო ჰ → ი
        if new_val.endswith("ჰ"):
            new_val = new_val[:-1]
            if not new_val.endswith("ი"):
                new_val = new_val + "ი"
        elif new_val.endswith("ჰი"):
            new_val = new_val[:-2] + "ი"
        # 2. ჩ → ქ (მაგ. აჩაია → აქაია)
        if "ჩ" in new_val:
            new_val = new_val.replace("ჩ", "ქ")
        # 3. ჯჰ → ია
        if "ჯჰ" in new_val:
            new_val = new_val.replace("ჯჰ", "ია")
        # 4. ჰ შუაში → მოხსნა (მაგ. აბიჰუ → აბიუ)
        # მაგრამ მხოლოდ თუ არ არის დასაწყისში
        if "ჰ" in new_val[1:]:
            new_val = new_val[0] + new_val[1:].replace("ჰ", "")
        
        if new_val != val and len(new_val) >= 3:
            topics[slug] = new_val
            phonetic_fixed += 1

    # შენახვა
    with open(os.path.join(DATA_DIR, "topic_names_ka.json"), "w", encoding="utf-8") as f:
        json.dump(topics, f, ensure_ascii=False, indent=2)

    # სტატისტიკა
    remaining = 0
    for val in topics.values():
        if val.startswith("I ") or val.startswith("II ") or val.startswith("III ") or val.startswith("IV "):
            continue
        if "ჰ" in val or "ჩ" in val:
            remaining += 1

    print(f"ლექსიკონით გასწორდა: {fixed}")
    print(f"ფონეტიკით გასწორდა: {phonetic_fixed}")
    print(f"დარჩენილი პრობლემური: {remaining}")


if __name__ == "__main__":
    main()
